Coverage 100% in api_client

diff --git a/letsencrypt_plesk/tests/testdata/psa/bin/secret_key b/letsencrypt_plesk/tests/testdata/psa/bin/secret_key
--- a/letsencrypt_plesk/tests/testdata/psa/bin/secret_key
+++ b/letsencrypt_plesk/tests/testdata/psa/bin/secret_key
@@ -1,2 +1,8 @@
 #!/bin/bash
-echo -n "3c4941c1-890b-5690-0c44f037ed1c"
+
+case "$1" in
+    "--create") echo -n "3c4941c1-890b-5690-0c44f037ed1c" ;;
+    "--delete") ;;
+    ""|"--help") echo "Usage: $(basename $0) --create" ;;
+    *) echo "Invalid argument: $1" && exit 1 ;;
+esac
